manifest:
  remotes:
	- name: zmkfirmware
	  url-base: https://github.com/zmkfirmware
    - name: michaeloverman
      url-base: https://github.com/michaeloverman
  projects:
    - name: zmk-config
      remote: michaeloverman
      revision: main
      import: app/west.yml
  self:
    path: config
