manifest:
  remotes:
    - name: michaeloverman
      url-base: https://github.com/michaeloverman
  projects:
    - name: zmk-config
      remote: michaeloverman
      revision: main
      import: config/west.yml
  self:
    path: config
