manifest:
  remotes:
    - name: michaeloverman
      url-base: https://github.com/michaeloverman
  projects:
    - name: zmk-config
      remote: michaeloverman/zmk-config
      revision: main
  self:
    path: config
