manifest:
  remotes:
    - name: michaeloverman
      url-base: https://github.com/michaeloverman
  projects:
    - name: zmk
      remote: michaeloverman
      revision: with-tap-dance
      import: app/west.yml
  self:
    path: config
